import { dirname, relative } from "node:path";

import { RUNTIME_PACKAGE } from "./analyze.js";
import type { ServerComponentDeclaration } from "./analyze.js";

export interface ServerComponentModule extends ServerComponentDeclaration {
  /** Absolute path of the authored server component module. */
  readonly file: string;
  /** Absolute path of its generated browser surrogate. */
  readonly surrogate: string;
}

const SOURCE_EXTENSION = ".ts";

function specifierFrom(fromFile: string, module: string): string {
  const path = relative(
    dirname(fromFile),
    module.endsWith(SOURCE_EXTENSION) ? module.slice(0, -SOURCE_EXTENSION.length) : module,
  );

  return path.startsWith(".") ? path : `./${path}`;
}

/**
 * The browser-graph surrogate of a server component: an ordinary Angular
 * component with the same selector, an empty template, the island host, and
 * the client references imported from the consumer's own modules. It owns
 * every client reference discovered under the server component, including
 * those beneath server-owned children and nested server components, whose
 * implementations it never imports.
 */
export function renderSurrogate(module: ServerComponentModule, root: string): string {
  // Recursive discovery can reach two client components with the same class
  // name from different modules: each gets a distinct local binding.
  const taken = new Set([
    "ChangeDetectionStrategy",
    "Component",
    "StrataIslandHost",
    "provideClientReferences",
    module.className,
  ]);
  const references = module.clientReferences.map((ref) => {
    let local = ref.name;

    for (let index = 2; taken.has(local); index++) local = `${ref.name}$${index}`;
    taken.add(local);

    return { ...ref, local };
  });
  const imports = references
    .map(
      (ref) =>
        `import { ${ref.local === ref.name ? ref.name : `${ref.name} as ${ref.local}`} } from "${specifierFrom(module.surrogate, ref.module)}";`,
    )
    .join("\n");

  return `// @generated by ${RUNTIME_PACKAGE}/vite — do not edit.
// Browser-graph surrogate for ${relative(root, module.file)}: the server
// component's implementation and server-only imports are absent by construction.
import { ChangeDetectionStrategy, Component } from "@angular/core";

import { StrataIslandHost, provideClientReferences } from "${RUNTIME_PACKAGE}";
${imports}

@Component({
  selector: ${JSON.stringify(module.selector)},
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: "",
  hostDirectives: [StrataIslandHost],
  providers: [provideClientReferences([${references.map((ref) => ref.local).join(", ")}])],
})
export class ${module.className} {}
`;
}
