import type { MatrixCase } from "./cases.ts";
import type { Diagnostic } from "./diagnostics.ts";
import { originSummary } from "./diagnostics.ts";

export interface TargetResult {
  installStatus: number | null;
  tscStatus: number | null;
  diagnostics: Diagnostic[];
  resolvedVersions: Record<string, string | null>;
}

export interface CaseResult {
  matrixCase: MatrixCase;
  h3Only: TargetResult;
  strataConsumer: TargetResult;
  eligible: boolean;
  eligibilityReason: string;
}

export interface AmbientControlResult {
  label: string;
  bunUnresolved: boolean;
  workersUnresolved: boolean;
}

export interface MismatchControlResult {
  found: boolean;
  origin: string | null;
  code: string | null;
}

export interface VersionMismatchControlResult {
  installFailedAsExpected: boolean;
}

export interface TypeClosureReport {
  generatedAt: string;
  baselineCommit: string;
  versions: {
    node: string;
    pnpmVersion: string;
    npmVersion: string;
  };
  cases: CaseResult[];
  ambientControls: AmbientControlResult[];
  mismatchControl: MismatchControlResult;
  versionMismatchControl: VersionMismatchControlResult;
  selfTestFailures: string[];
  infrastructureFailures: string[];
  promotedCandidate: string | null;
}

const MAX_MESSAGE_LENGTH = 240;

function truncateMessage(message: string): string {
  const singleLine = message.replace(/\|/g, "\\|");
  if (singleLine.length <= MAX_MESSAGE_LENGTH) return singleLine;
  return `${singleLine.slice(0, MAX_MESSAGE_LENGTH)}… (truncated, full text in raw tsc output)`;
}

const MAX_DIAGNOSTIC_ROWS = 40;

function diagnosticsTable(diagnostics: Diagnostic[]): string {
  if (diagnostics.length === 0) return "None.";

  const shown = diagnostics.slice(0, MAX_DIAGNOSTIC_ROWS);
  const rows = shown.map(
    (d) =>
      `| ${d.code} | ${d.origin} | ${d.file}:${d.line}:${d.column} | ${truncateMessage(d.message)} |`,
  );

  const omitted = diagnostics.length - shown.length;
  const omittedNote =
    omitted > 0
      ? `\n\n_${omitted} further diagnostic(s) omitted from this table; see the origin counts above for the complete distribution._`
      : "";

  return (
    ["| Code | Origin | Location | Message |", "| --- | --- | --- | --- |", ...rows].join("\n") +
    omittedNote
  );
}

function targetSection(title: string, result: TargetResult): string {
  const origins = originSummary(result.diagnostics);
  const originLines =
    Object.entries(origins)
      .map(([origin, count]) => `  - \`${origin}\`: ${count}`)
      .join("\n") || "  - (none)";

  return `**${title}**

- Install exit: ${result.installStatus}
- \`tsc --noEmit\` exit: ${result.tscStatus}
- Resolved versions: ${Object.entries(result.resolvedVersions)
    .map(([pkg, v]) => `\`${pkg}@${v ?? "(not installed)"}\``)
    .join(", ")}
- Diagnostic origin counts:
${originLines}

${diagnosticsTable(result.diagnostics)}
`;
}

function caseSection(result: CaseResult): string {
  const c = result.matrixCase;

  return `### Case ${c.id} — ${c.label}

${c.purpose}

- \`lib\`: \`${c.lib.join(", ")}\`
- \`types\`: \`${c.types.join(", ")}\`
- Extra dependencies: \`${JSON.stringify(c.dependencies)}\`
- Extra devDependencies: \`${JSON.stringify(c.devDependencies)}\`
- Activates foreign runtime ambient types: **${c.activatesForeignRuntimeTypes}**
- Eligible under SPEC-002 promotion rules: **${result.eligible}** — ${result.eligibilityReason}

${targetSection("H3-only reproduction", result.h3Only)}

${targetSection("Packed Strata consumer", result.strataConsumer)}
`;
}

export function renderReport(r: TypeClosureReport): string {
  const verdictSection = r.promotedCandidate
    ? `**Verdict: clean eligible candidate — \`${r.promotedCandidate}\`.**`
    : `**Verdict: upstream-blocked. No case satisfies SPEC-002's promotion rules.**`;

  return `# H3 consumer type closure evidence (SPEC-002)

Generated by \`pnpm test:consumer:types\` at ${r.generatedAt}, against baseline \`${r.baselineCommit}\`.
This report is regenerated on every run. It does not overwrite
[the SPEC-001 report](consumer-compilation.md); both are retained.

**Scope.** This experiment tests one hypothesis: whether explicit compiler libs and a closed set of
published type dependencies can qualify H3 v2 \`2.0.1-rc.32\` for a strict Node-only consumer, without
suppressions, patched declarations, or foreign runtime globals. It makes no Angular, Analog, Nitro,
browser, Bun or Cloudflare Workers *support* claim; Bun/Workers type packages are installed here only
as diagnostic controls.

## Versions

| Tool | Version |
| --- | --- |
| Node (actual) | ${r.versions.node} |
| pnpm | ${r.versions.pnpmVersion} |
| npm | ${r.versions.npmVersion} |

Per-case resolved \`h3\`/\`crossws\`/provider versions are reported in each case section below; the
fixed tuple targets are H3 \`2.0.1-rc.32\`, TypeScript \`6.0.3\`, \`@types/node\` \`22.20.3\`, \`srvx\`
\`1.0.5\`, \`rou3\` \`0.9.2\`, \`crossws\` \`0.4.12\`, \`@types/bun\`/\`bun-types\` \`1.4.2\`,
\`@cloudflare/workers-types\` \`5.20260917.1\`. SPEC-002 pins Node \`22.23.0\`; report actual Node
drift from that pin honestly rather than treating it as a silent substitution — it is an execution
environment detail, not a dependency resolution the matrix controls.

## Matrix cases A–D

${r.cases.map(caseSection).join("\n")}

## Negative ambient controls

Each row compiles a file that references only \`Bun\` and \`WebSocketPair\` (no H3, no Strata) under a
fixed \`lib\`/\`types\` set, to prove foreign-runtime-global availability is measured independently of
any H3 declaration diagnostic.

| Control | Bun unresolved (expected true for Node-only) | Workers unresolved (expected true for Node-only) |
| --- | --- | --- |
${r.ambientControls.map((c) => `| ${c.label} | ${c.bunUnresolved} | ${c.workersUnresolved} |`).join("\n")}

## AC5 disposable self-tests

- **Consumer-mismatch control**: a deliberate consumer-authored type error was ${r.mismatchControl.found ? "correctly detected" : "NOT detected"}
  ${r.mismatchControl.found ? `(code \`${r.mismatchControl.code}\`, origin \`${r.mismatchControl.origin}\`)` : ""},
  proving the classifier attributes an ordinary consumer mistake distinctly from upstream-origin diagnostics.
- **Dependency-version-mismatch control**: installing a disposable fixture with a nonexistent H3 version
  ${r.versionMismatchControl.installFailedAsExpected ? "correctly failed closed" : "did NOT fail as expected"}.

## Self-test integrity

${
  r.selfTestFailures.length === 0
    ? "All runner self-tests passed; the matrix evidence above is trustworthy."
    : r.selfTestFailures.map((f) => `- FAILED: ${f}`).join("\n")
}

## Infrastructure failures

${r.infrastructureFailures.length === 0 ? "None." : r.infrastructureFailures.map((f) => `- ${f}`).join("\n")}

## Verdict

${verdictSection}

Per SPEC-002's stop rules: B's \`esnext.error\` addition is a legitimate lib correction but insufficient
alone. C is eligible only if its entire declaration graph checks cleanly under Node-only types and the
negative ambient controls. D-node-only can only establish why the closure fails when providers are
installed but not activated. D-full-providers is never eligible for the Node contract even if clean,
because activating Bun/Workers ambient globals is itself disqualifying for a Node-only consumer claim —
and, per the diagnostics above, it does not typecheck cleanly regardless.

No packages under \`packages/\` were changed by this experiment. No Changeset is included: this slice is
tooling/research/compatibility qualification, not a public API or behavior change.
`;
}
