import { CLIENT_MARKER, CONTROLLER_MARKER, SERVER_MARKER } from "./constants.ts";

export type Outcome = "A" | "B" | "C" | "D";

export interface Check {
  name: string;
  passed: boolean;
  detail: string;
}

export interface CommandSummary {
  label: string;
  command: string;
  status: number | null;
}

export interface DependencyRow {
  name: string;
  declared: string;
  resolved: string;
  note: string;
}

export interface H3Resolution {
  consumer: string;
  version: string;
  createApp: boolean;
  createRouter: boolean;
  createEvent: boolean;
  H3: boolean;
}

/** One observed outcome for one (pipeline, mode) pair, with its recorded expectation. */
export interface Arm {
  id: string;
  pipeline: string;
  mode: string;
  expected: Outcome;
  observed: Outcome;
  evidence: string;
}

export interface SeamShape {
  typeofValue: string;
  constructorName: string | null;
  ownKeys: string[];
  hasOn: boolean;
  hasUse: boolean;
  hasStack: boolean;
}

export interface SeamSnapshot {
  nitroAppKeys: string[];
  h3App: SeamShape;
  router: SeamShape;
}

export interface MarkerScan {
  label: string;
  directory: string;
  serverMarker: string[];
  clientControlMarker: string[];
  coreInternalSymbol: string[];
  controllerMarker: string[];
  analogAdapterSymbol: string[];
  h3AdapterSymbol: string[];
}

export interface RouteRow {
  route: string;
  mode: string;
  status: number;
  contentType: string | null;
  body: string;
}

/** Observations about `@strata/analog` itself and the fixture that consumes it. */
export interface AdapterReport {
  manifest: {
    dependencies: Record<string, string>;
    peerDependencies: Record<string, string>;
    devDependencies: Record<string, string>;
    engines: string;
  };
  /** Bare module specifiers imported by the built package (JS and declarations). */
  builtImports: { file: string; specifiers: string[] }[];
  /** Every specifier the fixture uses to reach `@strata/analog`. */
  fixtureImports: string[];
  build: { status: number | null; artifacts: { path: string; exists: boolean }[] };
  routes: RouteRow[];
  typecheck: { command: string; status: number | null; note: string };
}

export interface AnalogReport {
  generatedAt: string;
  baselineCommit: string;
  node: string;
  pnpm: string;
  dependencies: DependencyRow[];
  lockfile: { name: string; versions: string[] }[];
  h3Resolutions: H3Resolution[];
  serverBundleH3: { file: string; createApp: boolean; createRouter: boolean; h3Class: boolean };
  nitro: { version: string; preset: string; previewCommand: string };
  commands: CommandSummary[];
  build: {
    status: number | null;
    artifacts: { path: string; exists: boolean; role: string }[];
  };
  arms: Arm[];
  nativeRoute: { mode: string; status: number; body: string }[];
  strataCore: { mode: string; status: number; body: string }[];
  seam: {
    snapshot: SeamSnapshot;
    h3RequirementSource: string;
    strataH3RequiresAppOn: boolean;
    outcome: Outcome;
    verdict: string;
  };
  markerScans: MarkerScan[];
  adapter: AdapterReport;
  checks: Check[];
  preWorkaroundFailure: string;
  upstreamMetadata: string;
}

const yesNo = (value: boolean): string => (value ? "yes" : "no");

const fence = (text: string, language = ""): string =>
  `\`\`\`${language}\n${text.trimEnd()}\n\`\`\``;

const code = (value: string): string => `\`${value}\``;

const indent = (text: string, prefix: string): string =>
  text
    .split("\n")
    .map((line) => (line === "" ? line : `${prefix}${line}`))
    .join("\n");

const cell = (value: string): string => value.replace(/\|/g, "\\|").replace(/\n/g, " ");

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const divider = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.map(cell).join(" | ")} |`);

  return [head, divider, ...body].join("\n");
}

function files(list: string[]): string {
  return list.length === 0 ? "none" : list.map(code).join(", ");
}

export function renderReport(report: AnalogReport): string {
  const failed = report.checks.filter((check) => !check.passed);
  const arm = (id: string): Arm | undefined => report.arms.find((candidate) => candidate.id === id);

  return `# Analog integration baseline

Generated by \`pnpm test:analog\` at ${report.generatedAt}. This report is regenerated on every run;
it reflects the most recent execution against baseline \`${report.baselineCommit}\`.

**Scope.** One question: how does the current \`@strata/core\` / \`@strata/h3\` fit inside a real
Angular + Analog application (\`apps/analog-fixture\`), built and run with the stock Analog
pipeline? No Strata Vite plugin and no decorator transform. \`@strata/core\` decorators are used
in \`src/server/**\`, and \`@strata/analog\` registers a controller on the Nitro router through Nitro's
public plugin API. It makes no claim beyond the single tuple below and the two modes exercised (dev
server, production server).

**Result of this run:** ${failed.length === 0 ? "every recorded expectation held" : `${failed.length} recorded expectation(s) did not hold — see Checks`}.

## Exact dependency tuple

Node ${report.node}, pnpm ${report.pnpm}. The fixture's manifests follow the official
\`create-analog@2.7.2\` \`template-latest\`. "Resolved" is read from the installed packages on disk
(symlinks followed), not from \`package.json\`.

${table(
  ["Package", "Declared", "Resolved", "Note"],
  report.dependencies.map((row) => [code(row.name), row.declared, row.resolved, row.note]),
)}

Lockfile (\`pnpm-lock.yaml\`, \`packages:\` section) — every version present in the whole workspace graph:

${table(
  ["Package", "Versions in lockfile"],
  report.lockfile.map((row) => [
    code(row.name),
    row.versions.length === 0 ? "none" : row.versions.join(", "),
  ]),
)}

## Runtime graph: which H3?

\`h3\` as resolved from each consumer, and the top-level APIs that copy actually exports
(loaded from disk, not inferred):

${table(
  ["Resolved from", "h3", "createApp", "createRouter", "createEvent", "H3 class"],
  report.h3Resolutions.map((row) => [
    row.consumer,
    row.version,
    yesNo(row.createApp),
    yesNo(row.createRouter),
    yesNo(row.createEvent),
    yesNo(row.H3),
  ]),
)}

- Resolved Nitro: **${report.nitro.version}** (\`nitropack\`, preset \`${report.nitro.preset}\`), recorded by the
  built server in \`dist/analog/nitro.json\`. Production start command: ${code(report.nitro.previewCommand)}.
- The built production server does not load an installed \`h3\`: Nitro inlines it into
  \`${report.serverBundleH3.file}\`, which defines \`createApp\`: **${yesNo(report.serverBundleH3.createApp)}**,
  \`createRouter\`: **${yesNo(report.serverBundleH3.createRouter)}** and an H3 v2 \`H3\` class:
  **${yesNo(report.serverBundleH3.h3Class)}**.
- Analog/Nitro run **H3 v1**; \`@strata/h3\` targets **H3 v2**. They are different majors with
  different APIs (\`createApp\`/\`createRouter\` vs the \`H3\` class).

## Angular/Analog compilation and standard decorators

The same consumer-authored \`@Controller()\` / \`@Get()\` (standard TC39 decorators from \`@strata/core\`)
was observed in the two places Analog compiles TypeScript. Classes: **A** works, **B** compile-time
failure, **C** build succeeds but runtime fails, **D** other.

${table(
  ["Arm", "Pipeline", "Mode", "Expected", "Observed", "Evidence"],
  report.arms.map((row) => [
    row.id,
    row.pipeline,
    row.mode,
    row.expected,
    row.observed === row.expected ? `**${row.observed}**` : `**${row.observed}** (drift)`,
    row.evidence,
  ]),
)}

- **Nitro server routes** (\`src/server/**\`, native Analog API routes) are bundled by Nitro's own
  Rollup + esbuild pipeline, not by the Angular compiler. esbuild lowers standard decorators on its
  own; \`getControllerDefinition()\` returns the right metadata in dev and production.
- **The Angular-compiled graph** (pages, components, anything a page imports) uses the stock
  Analog template's \`experimentalDecorators: true\`: the Angular compiler type-checks the consumer's
  decorators as *legacy* decorators and fails the build (class ${arm("G1")?.observed ?? "?"}). With
  \`experimentalDecorators: false\` the decorators are lowered and the metadata is correct in the dev
  server, but the production server's SSR of that page fails (class ${arm("G2-prod")?.observed ?? "?"}).
- Nothing here modified Strata or added a transform. The baseline build uses the stock
  \`vite.config.ts\`; the G arms use \`vite.probe.config.ts\`, which differs only by also building the
  probe page and by selecting which tsconfig Analog's Angular plugin reads.

## Production build

\`pnpm --filter @strata-fixtures/analog run build\` (\`vite build\`) exit status: **${String(report.build.status)}**.

${table(
  ["Artifact", "Present", "Role"],
  report.build.artifacts.map((row) => [code(row.path), yesNo(row.exists), row.role]),
)}

## Native Analog server route (\`/api/native\`)

${table(
  ["Mode", "Status", "Body"],
  report.nativeRoute.map((row) => [row.mode, String(row.status), code(row.body)]),
)}

## Strata metadata through \`@strata/core\` only (\`/api/strata-core\`)

${table(
  ["Mode", "Status", "Body"],
  report.strataCore.map((row) => [row.mode, String(row.status), code(row.body)]),
)}

## H3 seam and \`@strata/h3\`

Nitro hands its app to server plugins through the public \`defineNitroPlugin()\` from
\`nitropack/runtime\`; \`NitroApp.h3App\` and \`NitroApp.router\` are part of Nitro's exported
\`NitroApp\` type. A fixture plugin observed (never modified) what a real production server passes:

${fence(JSON.stringify(report.seam.snapshot, null, 2), "json")}

\`registerControllers()\` in \`@strata/h3\` (\`${report.seam.h3RequirementSource}\`) calls \`app.on(...)\`: **${yesNo(report.seam.strataH3RequiresAppOn)}**.
The Nitro \`h3App\` has \`.on\`: **${yesNo(report.seam.snapshot.h3App.hasOn)}**.

**Outcome ${report.seam.outcome}.** ${report.seam.verdict}

\`@strata/h3\` was **not** mounted in Analog: the only H3 app the public seam provides is an H3 v1
\`App\`, and passing it to a function typed for the H3 v2 \`H3\` class would need an unsafe cast
between majors, a fake H3 instance, or a second router — all ruled out for this experiment.

## \`@strata/analog\`: a Strata controller through the public Nitro router seam

\`src/server/plugins/strata.ts\` is a Nitro server plugin that calls
\`registerControllers(nitroApp.router, [UsersController])\`. \`UsersController\` (\`@Controller("/api/strata/users")\`
with two \`@Get()\` routes) is **not** reachable from any file under \`src/server/routes/**\`: no
file-system route wraps it. The routes below exist only because \`@strata/analog\` read its
\`@strata/core\` metadata and registered it on \`nitroApp.router\`.

${table(
  ["Route", "Mode", "Status", "Content-Type", "Body"],
  report.adapter.routes.map((row) => [
    code(row.route),
    row.mode,
    String(row.status),
    row.contentType ?? "none",
    code(row.body),
  ]),
)}

The native Analog route (\`/api/native\`, above) answers in the same run, on the same router.

**Package boundary.** \`@strata/analog\` declares:

${table(
  ["Field", "Value"],
  [
    ["dependencies", code(JSON.stringify(report.adapter.manifest.dependencies))],
    ["peerDependencies", code(JSON.stringify(report.adapter.manifest.peerDependencies))],
    ["devDependencies", code(JSON.stringify(report.adapter.manifest.devDependencies))],
    ["engines.node", code(report.adapter.manifest.engines)],
  ],
)}

Bare module specifiers in the built package (what a consumer's bundler and \`tsc\` must resolve):

${table(
  ["Built file", "Imports"],
  report.adapter.builtImports.map((row) => [code(row.file), files(row.specifiers)]),
)}

The fixture reaches the package only through ${report.adapter.fixtureImports.map(code).join(", ")}
(its \`exports\` entry, built \`dist\`).

**Type check against Nitro's real types.** ${report.adapter.typecheck.note}
Command: ${code(report.adapter.typecheck.command)} (exit ${String(report.adapter.typecheck.status)}).

## Server/client module graph baseline

\`${SERVER_MARKER}\` is used only from \`src/server/strata/hello.controller.ts\` (imported by Nitro
routes). \`${CLIENT_MARKER}\` is a positive control that lives in a client page, so a scan that finds it
proves the scanner can see client output at all.

${table(
  ["Output", "Server-only marker", "Client control marker", "@strata/core internal symbol"],
  report.markerScans.map((scan) => [
    `${scan.label} (${code(scan.directory)})`,
    files(scan.serverMarker),
    files(scan.clientControlMarker),
    files(scan.coreInternalSymbol),
  ]),
)}

\`${CONTROLLER_MARKER}\` is used only by the controller registered through \`@strata/analog\`
(\`src/server/strata/users.controller.ts\`, imported only by the Nitro plugin):

${table(
  [
    "Output",
    "Registered-controller marker",
    "`@strata/analog` (error class name)",
    "`@strata/h3` (error class name)",
  ],
  report.markerScans.map((scan) => [
    `${scan.label} (${code(scan.directory)})`,
    files(scan.controllerMarker),
    files(scan.analogAdapterSymbol),
    files(scan.h3AdapterSymbol),
  ]),
)}

Expected and observed: server output contains the server-only markers and the adapter; \`dist/client\`,
\`dist/analog/public\` and \`dist/ssr\` do not; no \`@strata/h3\` code is in any output. This is only a
baseline — nothing here is a Server Component or a guarantee for future code.

## Commands

${table(
  ["Step", "Command", "Exit"],
  report.commands.map((row) => [
    row.label,
    code(row.command),
    row.status === null ? "stopped by test" : String(row.status),
  ]),
)}

## Checks

${table(
  ["Check", "Result", "Detail"],
  report.checks.map((row) => [row.name, row.passed ? "pass" : "**FAIL**", row.detail]),
)}

## Blockers discovered

1. **H3 major mismatch at the seam.** Analog 2.7.2 → \`nitropack\` ${report.nitro.version} → H3 v1. The only
   public H3 handle (\`nitroApp.h3App\`) is an H3 v1 \`App\` with no \`.on()\`. \`@strata/h3\` needs an H3 v2
   \`H3\` instance, so it cannot mount directly (Outcome ${report.seam.outcome}). Resolved for Analog without
   touching it: \`@strata/analog\` is a sibling adapter on \`nitroApp.router\` and does not depend on
   \`@strata/h3\`. \`@strata/h3\` stays an H3 v2-only adapter.
2. **Phantom \`h3\` dependency in \`@analogjs/vite-plugin-nitro@2.7.2\`.** It imports \`h3\` without declaring
   it. Under pnpm's default hoisting, in a workspace that also contains \`@strata/h3\`, the bare import
   resolved to H3 v2 and the Vite config failed to load. This repo now declares the H3 major Nitro 2
   uses through \`packageExtensions\` in \`pnpm-workspace.yaml\` (workspace configuration only; no
   Strata code changed). Recorded failure before that workaround:

${indent(fence(report.preWorkaroundFailure), "   ")}

3. **Angular pipeline treats consumer decorators as legacy** with the stock \`experimentalDecorators: true\`
   (arm G1, class B). Turning it off makes the dev server work but exposes the next item.
4. **Production SSR of Angular-compiled standard decorators fails on \`tslib\`** (arm G2-prod, class C):
   TypeScript's standard-decorator lowering imports \`__esDecorate\`/\`__runInitializers\` from \`tslib\`
   (\`importHelpers: true\`); Nitro traces only \`tslib\`'s \`module\`-condition files, so Node's
   \`import\` + \`node\` resolution of \`tslib/modules/index.js\` fails at runtime. SSR then returns HTTP 200
   with an empty router outlet — a silent failure. Not investigated further or fixed here.
5. **Repo-wide Node floor (addressed).** \`@angular/build@22\` and \`create-analog@2.7.2\` require Node
   \`^22.22.3 || ^24.15.0 || >=26\`, and \`engine-strict=true\` makes \`pnpm install\` fail below that. The
   root/workspace development floor is now \`>=22.22.3\`. The public \`engines\` of \`@strata/core\`,
   \`@strata/h3\` and \`@strata/analog\` stay \`>=22\`: only the Angular fixture needs the higher patch.
   CI (\`node-version: 22\`) resolves the latest 22.x; that it satisfies the floor was not verified.
6. **Unchanged, not attempted:** the H3 v2 / crossws declaration blocker from SPEC-001/SPEC-002. The
   fixture never imports \`@strata/h3\`, so it neither triggers nor hides it.

Non-blocking observations from \`pnpm install\`: pnpm ignored the install scripts of \`esbuild\`,
\`@parcel/watcher\`, \`lmdb\` and \`msgpackr-extract\` (builds and servers worked without approving them),
and warns that \`@angular/build\` wants \`vitest@^4.0.8\` while the workspace root has \`vitest@5.0.1\`
(only used by Angular's own unit-test builder, which the fixture does not run).

## Other Analog lines (npm metadata only — not installed, not executed)

${report.upstreamMetadata}
`;
}
