interface CommandSummary {
  label: string;
  command: string;
  status: number;
}

interface TarballSummary {
  fileName: string;
  sha256: string;
  contents: string[];
}

interface StageExecution {
  assertion: string;
  error: string | null;
  stdoutExcerpt: string;
}

interface ProcessEvidence {
  status: number | null;
  stdout: string;
  stderr: string;
}

interface AcceptanceResult {
  status: "Pass" | "Fail" | "Blocked";
  evidence: string;
}

interface Blocker {
  id: string;
  summary: string;
  evidence: string;
}

export interface ConsumerReport {
  generatedAt: string;
  baselineCommit: string;
  versions: {
    node: string;
    pnpm: string;
    tsc: string;
    vite: string;
    h3Resolved: string;
    rolldown: string;
  };
  commands: CommandSummary[];
  tarballs: {
    core: TarballSummary;
    h3: TarballSummary;
  };
  dependencyRewrite: {
    h3PackedCoreDependency: string;
    containsWorkspaceProtocol: boolean;
  };
  install: {
    coreCopyPaths: string[];
    resolvedH3Version: string;
  };
  reference: {
    tsc: ProcessEvidence & { emitted: boolean };
    stage1Execution: StageExecution;
    viteBuild: ProcessEvidence;
    stage2Execution: StageExecution;
  };
  directVite: {
    build: ProcessEvidence;
    execution: ProcessEvidence;
    outcome: string;
  };
  symbolPreservation: {
    status: number | null;
    passed: boolean;
  };
  negativeControls: {
    missingTarball: { triggered: boolean; npmStatus: number };
    corruptedResponse: { detected: boolean };
  };
  acceptance: Record<string, AcceptanceResult>;
  blockers: Blocker[];
  tempDir: string;
  cleanedUp: boolean;
}

function codeBlock(text: string, lang = ""): string {
  const body = text && text.trim().length > 0 ? text.trim() : "(empty)";
  return `\`\`\`${lang}\n${body}\n\`\`\``;
}

function acceptanceTable(acceptance: Record<string, AcceptanceResult>): string {
  const rows = Object.entries(acceptance).map(
    ([id, { status, evidence }]) => `| ${id} | ${status} | ${evidence} |`,
  );

  return ["| ID | Status | Evidence |", "| --- | --- | --- |", ...rows].join("\n");
}

export function renderReport(r: ConsumerReport): string {
  return `# Consumer compilation evidence (SPEC-001)

Generated by \`pnpm test:consumer\` at ${r.generatedAt}. This report is regenerated on every run;
it reflects the most recent execution against baseline \`${r.baselineCommit}\`.

**Scope.** This is a single Node.js consumer recipe (tsc → Vite SSR bundle → Node execution, plus a
stock-Vite characterization arm) for \`@strata/core\`/\`@strata/h3\` tarballs installed outside the
workspace. It makes **no** Angular, Analog, Nitro, browser, or Cloudflare compatibility claim.

## Versions

| Tool | Version |
| --- | --- |
| Node | ${r.versions.node} |
| pnpm | ${r.versions.pnpm} |
| TypeScript (consumer-local) | ${r.versions.tsc} |
| Vite (consumer-local) | ${r.versions.vite} |
| h3 (consumer-local, resolved) | ${r.versions.h3Resolved} |
| Rolldown (workspace lockfile) | ${r.versions.rolldown} |

## Commands

${r.commands.map((c) => `- \`${c.command}\` → exit ${c.status}`).join("\n")}

## Tarball identity

| Package | Tarball | SHA-256 |
| --- | --- | --- |
| @strata/core | \`${r.tarballs.core.fileName}\` | \`${r.tarballs.core.sha256}\` |
| @strata/h3 | \`${r.tarballs.h3.fileName}\` | \`${r.tarballs.h3.sha256}\` |

<details><summary>@strata/core tarball contents</summary>

${codeBlock(r.tarballs.core.contents.join("\n"))}

</details>

<details><summary>@strata/h3 tarball contents</summary>

${codeBlock(r.tarballs.h3.contents.join("\n"))}

</details>

## Dependency graph

- Packed \`@strata/h3\` \`dependencies["@strata/core"]\` = \`${r.dependencyRewrite.h3PackedCoreDependency}\`
  (contains \`workspace:\`: **${r.dependencyRewrite.containsWorkspaceProtocol}**).
- Isolated consumer install resolved **${r.install.coreCopyPaths.length}** copy/copies of \`@strata/core\`:
  ${r.install.coreCopyPaths.map((p) => `\`${p}\``).join(", ") || "(none found)"}.
- Isolated consumer resolved \`h3@${r.install.resolvedH3Version}\` (expected \`2.0.1-rc.32\`).

## Reference recipe (tsc → Vite → Node)

### Stage 1 — consumer-local \`tsc\`

- Exit code: **${r.reference.tsc.status}** (0 = clean typecheck).
- JS emitted despite diagnostics: **${r.reference.tsc.emitted}**.

<details><summary>tsc diagnostics</summary>

${codeBlock(r.reference.tsc.stdout + r.reference.tsc.stderr)}

</details>

- Execution of tsc-emitted JS in a fresh Node process: **${r.reference.stage1Execution.assertion}**
  ${r.reference.stage1Execution.error ? `— ${r.reference.stage1Execution.error}` : ""}

<details><summary>stage 1 execution output</summary>

${codeBlock(r.reference.stage1Execution.stdoutExcerpt)}

</details>

### Stage 2 — consumer-local Vite (SSR bundle of the tsc output)

- Vite build exit code: **${r.reference.viteBuild.status}**.

<details><summary>vite build output</summary>

${codeBlock(r.reference.viteBuild.stdout + r.reference.viteBuild.stderr)}

</details>

- Execution of the Vite-bundled reference output in a fresh Node process: **${r.reference.stage2Execution.assertion}**
  ${r.reference.stage2Execution.error ? `— ${r.reference.stage2Execution.error}` : ""}

## Direct-Vite characterization (no decorator lowering)

- Vite build exit code: **${r.directVite.build.status}**.
- Recorded outcome: **${r.directVite.outcome}** (one of \`works\`, \`build_failed\`, \`runtime_failed\`).

<details><summary>direct-Vite build output</summary>

${codeBlock(r.directVite.build.stdout + r.directVite.build.stderr)}

</details>

<details><summary>direct-Vite execution output</summary>

${codeBlock(r.directVite.execution.stdout + r.directVite.execution.stderr)}

</details>

## Guarded metadata symbol

- A \`Symbol.metadata\` set before importing \`@strata/core\` in an isolated process
  remained unchanged after import: **${r.symbolPreservation.passed}**.

## Negative controls

- Missing tarball → install failure propagated: **${r.negativeControls.missingTarball.triggered}**
  (npm exit ${r.negativeControls.missingTarball.npmStatus}).
- Deliberately corrupted expected response → assertion helper detected it: **${r.negativeControls.corruptedResponse.detected}**.

## Acceptance criteria evidence

${acceptanceTable(r.acceptance)}

## Blockers

${
  r.blockers.length === 0
    ? "None."
    : r.blockers
        .map(
          (b) =>
            `### ${b.id}: ${b.summary}\n\n${b.evidence}\n\n**Owner:** not \`@strata/core\`/\`@strata/h3\` — see evidence above. Requires a separate fix spec from Astra.\n`,
        )
        .join("\n")
}

## Temporary directory

${r.cleanedUp ? "Removed on success." : `Left on disk for inspection: \`${r.tempDir}\``}
`;
}
